name: Instrumentation Test CI

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        api-level: [ 21, 29, 30 ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Get AVD target
        uses: ./.github/actions/get-avd-target
        id: avd-info
        with:
          api-level: ${{ matrix.api-level }}

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          target: ${{ steps.avd-info.outputs.target }}
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Update MAPS_API_SECRET
        env:
          MAPS_API_KEY: ${{secrets.MAPS_API_KEY}}
        run: echo MAPS_API_KEY="$MAPS_API_KEY" > ./local.properties


      - name: Run tests
        uses: ReactiveCircus/android-emulator-runner@v2.27.0
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          target: ${{ steps.avd-info.outputs.target }}
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
